on:
  push:
  schedule:
    - cron:  '0 4 * * 1'
jobs:
  backup_freshrss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: black-desk/freshrss-backup@v1
        with:
          base_url: ${{ secrets.freshrss_url }}
          username: ${{ secrets.freshrss_username }}
          password: ${{ secrets.freshrss_password }}
          target: freshrss
      - uses: stefanzweifel/git-auto-commit-action@v4
